### ISSUE TITLE
'function' is recognized in all the wrong places

### ISSUE THREAD

**Issue by CodeFloh** [rscircus/fortress#4] opened 2016-05-31 14:32 UTC
unwrapped_line.py, l. 291: This is not very safe. The word 'function' is even recognized as influencing the indentation when it's used inside a character string. Somehow, we need to check more carefully for this keyword.

**Comment by rscircus** [comment] 2016-05-31 17:54
Duplicate of https://github.com/rscircus/fortress/issues/2 (sorry for the cnfsn, clicked the wrong tab, #5 is valid).

**Comment by CodeFloh** [comment] 2016-06-01 08:45
Actually, recognizing 'function' anywhere **outside of strings** is fine. But we need to ignore strings. I will improve this to solve this issue, but I'm opening a separate issue concerning the indentation.

**Closed as completed** 2016-06-01 09:36 UTC
