### ISSUE TITLE
Continuations inside character strings are treated wrongly

### ISSUE THREAD

**Issue by CodeFloh** [rscircus/fortress#5] opened 2016-05-31 14:35 UTC
When a character string is wrapped, the program currently does not preserve the string exactly. This is what is called 'tight continuations' in the code. This needs to be recognized more safely, to avoid removing or adding spaces.

**Comment by rscircus** [comment] 2016-05-31 17:26
Note http://fortranwiki.org/fortran/show/Continuation+lines

**Comment by rscircus** [comment] 2016-05-31 17:52
Duplicate of https://github.com/rscircus/fortress/issues/2

**Closed as completed** 2016-06-01 07:58 UTC
